تمرینات numpy

In [1]:
import numpy as np

In [9]:
q3 = np.array([[5,2, 1,4], [2, 1, 4,5], [1, 3, 5,-1],[1, 3, 5,4],[1, 3, 5,4]])
q3<=5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
q3_1= np.full((4, 5),True)
q3_1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [10]:
q3_1= np.ones((4, 5), dtype = int)
q3_1>0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [12]:
np.random.seed(123)
q4 = np.random.randint(10, 50, (4,5))
q4

array([[12, 38, 44, 48, 27],
       [29, 32, 43, 42, 19],
       [42, 42, 35, 29, 24],
       [46, 42, 26, 14, 13]])

In [15]:
a = np.arange(10, 70, 3).reshape(4, 5)
a[a % 2 == 0] = -1  
a

array([[-1, 13, -1, 19, -1],
       [25, -1, 31, -1, 37],
       [-1, 43, -1, 49, -1],
       [55, -1, 61, -1, 67]])

In [17]:
q5 = np.arange(1, 21, 2)
q5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
q5[q5 % 3 == 0] = 0
q5

array([ 1,  0,  5,  7,  0, 11, 13,  0, 17, 19])

In [21]:
matrix = q5.reshape(2, 5)
matrix

array([[ 1,  0,  5,  7,  0],
       [11, 13,  0, 17, 19]])

In [22]:
matrix[:, 2] = 0
matrix

array([[ 1,  0,  0,  7,  0],
       [11, 13,  0, 17, 19]])

a: Create an one-dimensional array, b1, which includes 9 numbers evenly spaced over 1.5 to 3

In [35]:
b1 = np.linspace(1.5, 3, 9)
b1


array([1.5   , 1.6875, 1.875 , 2.0625, 2.25  , 2.4375, 2.625 , 2.8125,
       3.    ])

b: Create a 3x3 matrix, b2, which includes random numbers from Gaussian distribution with mean = 1, and sd = 0.75, seed = 1234.

In [30]:
np.random.seed(1234)
b2 = np.random.normal(1, 0.75, (3, 3))
b2


array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

c: Calculate the determinant of b2.

In [31]:
det_b2 = np.linalg.det(b2)
det_b2

-1.0770051050177027

d: What is the transpose of matrix b2?

In [32]:
transpose_b2 = b2.T 
transpose_b2


array([[1.35357637, 0.76551108, 1.64469131],
       [0.10676823, 0.45955845, 0.52260737],
       [2.07453023, 1.66537221, 1.01177228]])

e: Convert b1 into a 3x3 matrix.

In [37]:
b1_matrix = b1.reshape(3, 3)
b1_matrix


array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

f: Calculate summation of b1 and b2.

In [38]:
sum_b1_b2 = b1_matrix + b2
sum_b1_b2


array([[2.85357637, 1.79426823, 3.94953023],
       [2.82801108, 2.70955845, 4.10287221],
       [4.26969131, 3.33510737, 4.01177228]])

g: Calculate matrix multiplication of b1 and b2.

In [39]:
mult_b1_b2 = np.matmul(b1_matrix, b2)
mult_b1_b2

array([[ 6.40596071,  1.91554605,  7.81918396],
       [ 8.52308626,  2.52807145, 10.49200098],
       [10.64021182,  3.14059686, 13.16481801]])

h: Call all numbers of b2 which are greater than mean of b2.

In [41]:
mean_b2 = np.mean(b2)
greater_than_mean = b2[b2 > mean_b2]
greater_than_mean


array([1.35357637, 2.07453023, 1.66537221, 1.64469131])

i: Scale matrix b2 using min-max scaling method.

In [42]:
b2_min = np.min(b2)
b2_max = np.max(b2)
b2_scaled = (b2 - b2_min) / (b2_max - b2_min)
b2_scaled

array([[0.63361735, 0.        , 1.        ],
       [0.33476754, 0.17928501, 0.79206936],
       [0.7815595 , 0.21132593, 0.4599154 ]])